# Generated by Django 2.1.3 on 2018-12-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Everything',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=200)),
                ('urlToImage', models.CharField(max_length=500, null=True)),
                ('publishedAt', models.DateTimeField(verbose_name='date_published')),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sources',
            unique_together={('name', 'description', 'url', 'category', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='everything',
            unique_together={('name', 'description', 'url', 'urlToImage', 'publishedAt')},
        ),
    ]
